### ISSUE TITLE
Weather data unreachable

### ISSUE THREAD

**Issue by kaptoxic** [Neroth/gnome-shell-extension-weather#226]
I am getting these errors (Gnome 3.16):
```
gnome-session[2482]: (gnome-shell:24757): GWeather-WARNING **: Failed to get IWIN forecast data: 403 Forbidden
```

**Comment by ferdnyc** [comment]
See my PR #224 for the (one-line) fix.

**Comment by kaptoxic** [comment]
Thanks. I am looking forward to see this merged.

**Comment by ferdnyc** [comment]
As it has been, since October 10. So I guess this can be closed?

**Comment by kaptoxic** [comment]
Yes, great, that seems to be the case.
