### ISSUE TITLE
GNOME 3.20 Support

### ISSUE THREAD

**Issue by brinox** [Neroth/gnome-shell-extension-weather#229]
Arch Linux made gnome-shell 3.20.0 available yesterday, please add support for that version.

**Comment by SettRaziel** [comment]
Hej. I changed the line in the file metadata.json to
 `"shell-version": [ "3.8", "3.10", "3.12", "3.14", "3.16", "3.18", "3.20" ],`
and this seems to work fine. Didn't have a problem with the extension so far.
I instaalled the extension via aur, so i found the file in 
/usr/share/gnome-shell/extensions/weather-extension@xeked.com/.
If you installed it manually, you should found the path to the metadata.json by looking into 
/home/<username>/.local/share/gnome-shell/extensions and checking if there is a link to the folder of the extension.

**Comment by Neroth** [comment]
Done in the last commit ( 749bd0d ). Thanks.
