### ISSUE TITLE
Doesn't update the weather data anymore

### ISSUE THREAD

**Issue by Th0rleif** [Neroth/gnome-shell-extension-weather#232]
Hi,
For few days now, the exetension doesn't show/get the weather data.
I tried to recompile the extension against any potential upgraded lib but nothing has changed.
I haven't seen any errors looking to the extension console (Alt+F2 then 'lg'). My machine is running under Archlinux and Gnome 3.20.2 is installed.
Has anyone encountered that issue? What extra info would you need to investigate the that?
regards,

**Comment by ferdnyc** [comment]
This is due to a libgweather breakage, which came about due to a service deprecation by the NOAA. A new libgweather should be out shortly that will fix both the gnome-weather app and this extension.

https://bugzilla.gnome.org/show_bug.cgi?id=770321

**Comment by Th0rleif** [comment]
Ok, thank you for the answer. So I will keep patient and going to check what happens behind my shutters.

**Comment by ferdnyc** [comment]
(From an old 1990s NYC radio morning-show bit, in Homer Simpson's voice:) "If you want to know the weather, stick your head out the window. If it gets wet, it's raining. If it gets stolen, you're in New York City!"
