### ISSUE TITLE
Error: GWeather.Location.new_world is not a function

### ISSUE THREAD

**Issue by averissimo** [Neroth/gnome-shell-extension-weather#242]
Extension is crashing with the error on the title.

On ubuntu bionic with both versions from extensions' site and git repository

- gnome-weather is already the newest version (3.26.0-4)

![image](https://user-images.githubusercontent.com/211358/37984863-527d728a-31ef-11e8-8b74-5ba14acc5ec6.png)

**Comment by luktom** [comment]
It crashing because gnome-weather API has been changed recently. I've created a pull request with the fix: https://github.com/Neroth/gnome-shell-extension-weather/pull/243

**Comment by navarroaxel** [comment]
could you publish to https://extensions.gnome.org/extension/613/weather/ please? thanks!

**Comment by averissimo** [comment]
I am closing the issue as PR has been merged and I was able to confirm it works.

@navarroaxel better ask in pull request #243 or the dev
